config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :github do
    get 'repositories', to: 'repositories#index'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/github/repositories_controller.rb
module Github
  class RepositoriesController < ApplicationController
    def index
      return unless search_query[:query].present?

      github_client = GithubClient.new
      page = search_query[:page] || 1
      @response = github_client.search_repositories(query: search_query[:query], page:)

      render :index, status: :ok
    end

    private

    def search_query
      params.permit(:query, :page)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/github/repositories_helper.rb
# frozen_string_literal: true

module Github
  module RepositoriesHelper
  end
end

app/views/github/repositories/_repositories.html.erb
<% if @response.present? %>
	<ul class="list">
		<% @response[:page_items].each do |repository| %>
			<li class="list-item">
				<%= link_to(repository[:url], target: "_blank", rel: "nofollow") do %>
					<div class="list-item-header">
						<strong><%= repository[:name] %></strong>
						<div class="list-icons">
							<div>
								<i class="fa fa-star"></i>
							<%= repository[:stars] %>
							</div>
							<div>
								<i class="fa fa-code-fork"></i>
								<%= repository[:forks] %>
							</div>
						</div>
					</div>

					<span>
						<%= repository[:description] %>
					</span>
				<% end  %>
			</li>
		<% end %>
		<li class="list-item list-item-actions">
			<%= link_to 'First Page',github_repositories_path(:query => params[:query], :page => @response[:first]),
				class: "#{'disabled' unless @response[:first].present?}" %>
			<%= link_to 'Previous Page', github_repositories_path(:query => params[:query], :page => @response[:prev]),
				class: "#{'disabled' unless @response[:prev].present?}" %>
			<%= link_to 'Next Page', github_repositories_path(:query => params[:query], :page => @response[:next]),
				class: "#{'disabled' unless @response[:next].present?}" %>
			<%= link_to 'Last Page', github_repositories_path(:query => params[:query], :page => @response[:last]),
				class: "#{'disabled' unless @response[:last].present?}" %>
		</li>
	</ul>
<% end %>

<% if @response == false %>
	<div class="error">
		<i class="fa fa-meh-o"></i>
		Oh no! Something's not quite right...
	</div>
<% end %>

app/views/github/repositories/index.html.erb
<div class="page">
    <div class="header">
        <%= link_to(github_repositories_path) do %>
            Adjust Challenge: GitHub Repository Search
        <% end %>
    </div>

    <div class="content">
        <div class="form">
            <%= form_tag github_repositories_path, :method => "get" do %>
                <%= text_field_tag :query, params[:query], placeholder:'Enter repository name' %>
            <% end %>
        </div>

        <%= render 'repositories'%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdjustChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>